import {useState} from 'react';
import {builtinPack} from '../cards/builtin.ts';
import type {CardPack} from '../cards/schema.ts';
import {subsetPack} from '../cards/pack.ts';
import {database} from '../persistence/database.ts';
import {downloadPack,errorText,readPackFile} from '../cards/browser.ts';
import {CardAvatar} from './DeckBuilder.tsx';
export function CardLibrary({packs,onChange,onClose}:{packs:CardPack[];onChange:(packs:CardPack[])=>void;onClose:()=>void}){
 const [pending,setPending]=useState<CardPack|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<string|null>(null);
 const [selection,setSelection]=useState<Record<string,string[]>>({});
 const old=pending?packs.find(p=>p.id===pending.id):null;
 async function commit(){if(!pending||busy)return;setBusy(true);try{const result=await database().importPack(pending,old?.revision);onChange(await database().listPacks());setPending(null);setMessage(result==='duplicate'?'이미 같은 카드팩이 있습니다.':result==='updated'?'카드팩을 갱신했습니다. 다음 새 선수부터 적용됩니다.':'카드팩을 추가했습니다. 새 선수의 덱에서 고를 수 있습니다.');}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 return <><h1 className="screen-title" tabIndex={-1}>서포트 카드 라이브러리</h1><p className="lead">직접 만든 인물과 함께 새로운 야구를 시작하세요. 카드팩을 바꿔도 진행 중인 선수의 덱은 그대로 유지됩니다.</p><div className="actions"><label className="file-button">카드팩 가져오기<input type="file" accept=".cardpack,.zip,.json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setMessage('');setPending(null);try{setPending(await readPackFile(file));}catch(error){setMessage(errorText(error));}finally{setBusy(false);}}}/></label><a className="button-link" href="/card-editor/" target="_blank" rel="noreferrer">카드 제작기 열기 ↗</a><button onClick={onClose}>처음 화면으로</button></div>
 {message&&<p className="notice preserve-lines" role="status">{message}</p>}{busy&&<p role="status">카드팩을 처리하고 있습니다…</p>}
 {pending&&<section className="panel import-preview"><h2>가져오기 미리 보기 · {pending.name}</h2><p>{pending.author||'제작자 미지정'} · 개정 {pending.revision} · 카드 {pending.cards.length}장 · 그림 {Object.keys(pending.images).length}개</p><p>{pending.cards.map(c=>c.name).join(' · ')}</p>{old&&<p className="warning">같은 팩의 개정 {old.revision}이 있습니다. 더 높은 개정만 갱신할 수 있습니다.</p>}<div className="actions"><button className="primary" disabled={busy} onClick={()=>void commit()}>{old?'확인 후 카드팩 갱신':'카드팩 등록'}</button><button disabled={busy} onClick={()=>setPending(null)}>취소</button></div></section>}
 {[builtinPack,...packs].map(p=><section className="panel library-pack" key={p.id}><h2>{p.name}</h2><p className="reason">{p.id} · 개정 {p.revision} · {p.author||'제작자 미지정'} · {p.cards.length}장</p><p>{p.description}</p><div className="library-cards">{p.cards.map(c=><label key={c.id}><input type="checkbox" checked={(selection[p.id]||[]).includes(c.id)} onChange={e=>setSelection({...selection,[p.id]:e.target.checked?[...(selection[p.id]||[]),c.id]:(selection[p.id]||[]).filter(id=>id!==c.id)})}/><CardAvatar card={c} content={p}/><span>{c.name}<small>{c.title}</small></span></label>)}</div><div className="actions"><button onClick={()=>{try{downloadPack(p);}catch(e){setMessage(errorText(e));}}}>전체 팩 내보내기</button><button disabled={!selection[p.id]?.length} onClick={()=>{try{downloadPack(subsetPack(p,selection[p.id]));}catch(e){setMessage(errorText(e));}}}>선택 카드 내보내기 ({selection[p.id]?.length||0})</button>{p.id!=='core'&&<button onClick={()=>setDeleting(p.id)}>팩 삭제</button>}</div>{deleting===p.id&&<div className="confirm-box"><p>{p.name}을 라이브러리에서 삭제할까요? 진행 중인 덱과 이미 받은 파일은 유지됩니다.</p><div className="actions"><button disabled={busy} onClick={async()=>{setBusy(true);try{await database().removePack(p.id);onChange(await database().listPacks());setDeleting(null);setMessage('카드팩을 삭제했습니다.');}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}}>삭제 확인</button><button onClick={()=>setDeleting(null)}>취소</button></div></div>}</section>)}</>;
}
