import {readDraftPack} from '../cards/draft.ts';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {CardPack,SupportCard,SkillDefinition,EncounterDefinition} from '../cards/schema.ts';
import {primaryNames,requirementNames,skillAbilityNames} from '../cards/schema.ts';
import {newDraft,duplicateCard,deleteCard,addTemplate,previewCard,addSkillPair,setCardImage,setCardSkill} from '../cards/authoring.ts';
import {base64,subsetPack,validatePack} from '../cards/pack.ts';
import {downloadPack,errorText,readPackFile} from '../cards/browser.ts';
import {describeSkill} from '../cards/description.ts';
import {database} from '../persistence/database.ts';
import {primaryLabels,labels} from '../game/types.ts';
import type {Role} from '../game/types.ts';
import {activities} from '../content/activities.ts';
import {effectChips} from '../game/engine.ts';
import {CardAvatar} from '../ui/DeckBuilder.tsx';
import {TextField,NumberField,ConditionFields,EffectFields} from './Fields.tsx';
const roles=['batter','pitcher'] as const;
const roleLabel=(role:Role)=>role==='batter'?'타자':'투수';
const uid=()=>`card_${crypto.randomUUID().replaceAll('-','').slice(0,12)}`;

function Preview({pack,card}:{pack:CardPack;card:SupportCard}){
 const [role,setRole]=useState<Role>('batter'),[bond,setBond]=useState(60),[learned,setLearned]=useState<'none'|'normal'|'upper'>('upper');
 const [context,setContext]=useState({inning:7,outs:2,energy:40,stress:30,runners:true,behind:true});
 let preview:ReturnType<typeof previewCard>|null=null,error='';try{preview=previewCard(pack,card.id,role,bond,learned,context);}catch(e){error=errorText(e);}
 return <section className="panel"><h2>실제 규칙으로 미리 보기</h2><p className="reason">입학 능력과 지능 290를 기준으로 이 카드 한 장만 동행시킵니다. 상위 미리 보기는 습득 조건을 충족했다고 가정합니다. 난수를 소비하지 않습니다.</p><div className="editor-row"><label className="editor-field">선수 역할<select value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option value={r} key={r}>{roleLabel(r)}</option>)}</select></label><NumberField label="인연" value={bond} min={0} max={100} onChange={setBond}/><label className="editor-field">습득 스킬<select value={learned} onChange={e=>setLearned(e.target.value as typeof learned)}><option value="none">없음</option><option value="normal">일반</option><option value="upper">상위 (일반 대체)</option></select></label>{(['inning','outs','energy','stress'] as const).map(k=><NumberField key={k} label={{inning:'이닝',outs:'아웃',energy:'현재 체력',stress:'현재 스트레스'}[k]} value={context[k]} min={k==='inning'?1:0} max={k==='inning'?99:k==='outs'?2:100} onChange={v=>setContext({...context,[k]:v})}/>)}</div><div className="editor-row"><label><input type="checkbox" checked={context.runners} onChange={e=>setContext({...context,runners:e.target.checked})}/>주자 있음</label><label><input type="checkbox" checked={context.behind} onChange={e=>setContext({...context,behind:e.target.checked})}/>우리 팀이 지는 중</label></div>
 {error?<p className="notice warning preserve-lines">먼저 카드팩 검사를 통과해 주세요.
{error}</p>:preview&&<><h3>{preview.activity.title} · 동행 시 성장</h3><div className="chips">{effectChips(preview.activity).map(c=><span className="chip" key={c.key}>{c.label}</span>)}</div><p className="reason">실패 {preview.activity.failureChance}% · 스킬 +{preview.activity.points} Pt · 인연 보너스 포함</p><div className="preview-table"><table><thead><tr><th>경기 작전</th><th>평균 결과 확률 · 스킬 반영</th><th>투구 부담</th></tr></thead><tbody>{preview.tactics.map(t=><tr key={t.id}><th>{t.title}</th><td>{t.probabilities.map((p,i)=>p>0?<span key={i} className="block">{['삼진','범타·병살','볼넷·사구','안타','2·3루타','홈런','희생타','실책 출루'][i]} {(p*100).toFixed(1)}% <small>({((p-preview!.base.find(x=>x.id===t.id)!.probabilities[i])*100).toFixed(1)}%p)</small></span>:null)}<p className="reason">{t.reason}</p></td><td>{t.burden.toFixed(2)}</td></tr>)}</tbody></table></div></>}
 </section>;
}

export default function Editor(){
 const [pack,setPack]=useState<CardPack>(newDraft),[selected,setSelected]=useState('classmate'),[tab,setTab]=useState('인물');
 const [ready,setReady]=useState(false),[draftBlocked,setDraftBlocked]=useState(false),[saved,setSaved]=useState('초안을 읽고 있습니다…');
 const [message,setMessage]=useState(''),[pending,setPending]=useState<CardPack|null>(null),[confirmation,setConfirmation]=useState<'new'|'delete'|null>(null);
 const queue=useRef(Promise.resolve()),ticket=useRef(0);
 useEffect(()=>{let cancel=false;void (async()=>{try{const raw=await database().readDraft();if(cancel)return;if(raw){const parsed=readDraftPack(raw);setPack(parsed);setSelected(parsed.cards[0]?.id||'');}setSaved('초안 준비됨');}catch(e){if(!cancel){setMessage(errorText(e));setDraftBlocked(true);setSaved('기존 초안을 보존하고 있습니다.');}}finally{if(!cancel)setReady(true);}})();return()=>{cancel=true;};},[]);
 const validation=useMemo(()=>{try{validatePack(pack);return '';}catch(e){return errorText(e);}},[pack]);
 useEffect(()=>{
  if(!ready||draftBlocked)return;
  const n=++ticket.current;setSaved('초안 저장 중…');
  const value=JSON.stringify({format:'editor-draft-1',pack});
  const timer=setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(async()=>{try{await database().writeDraft(value);if(n===ticket.current)setSaved('초안 자동 저장됨');}catch(e){if(n===ticket.current){setSaved('초안 저장 실패');setMessage(errorText(e));}}});},300);
  return()=>clearTimeout(timer);
 },[pack,ready,draftBlocked]);
 function update(fn:(p:CardPack)=>void){setPack(previous=>{const p=structuredClone(previous);fn(p);return p;});}
 const card=pack.cards.find(c=>c.id===selected)||pack.cards[0];
 const changeCard=(fn:(c:SupportCard)=>void)=>update(p=>fn(p.cards.find(c=>c.id===card.id)!));
 function perform(fn:()=>void){try{fn();setMessage('');}catch(e){setMessage(errorText(e));}}
 function replace(p:CardPack){setPack(p);setSelected(p.cards[0]?.id||'');setTab('인물');setPending(null);setDraftBlocked(false);setConfirmation(null);}
 const cardSkills=card?new Set([...Object.values(card.hints),...Object.values(card.ultimates)].filter(Boolean)):new Set<string>();
 const cardEvents=card?pack.events.filter(e=>e.owner===card.id):[];
 return <div className="editor-app"><header className="editor-header"><div><p className="eyebrow">LAST SUMMER / CARD STUDIO</p><h1>나만의 야구 파트너</h1><p>인물부터 마지막 성장 사건까지, 한 장의 서포트에 담아보세요.</p></div><a href="/" className="button-link">게임으로 돌아가기</a></header>
 <div className="editor-toolbar"><label className="file-button">카드팩 열기<input type="file" accept=".cardpack,.zip,.json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{setPending(await readPackFile(file));setMessage('');}catch(error){setMessage(errorText(error));}}}/></label><button onClick={()=>setConfirmation('new')}>새 팩</button><button disabled={!!validation} onClick={()=>perform(()=>downloadPack(pack))}>전체 팩 내보내기</button><button disabled={!!validation||!card} onClick={()=>perform(()=>downloadPack(subsetPack(pack,[card.id])))}>현재 카드 내보내기</button><button onClick={()=>setMessage(validation||'검사 통과 · 게임에서 가져올 수 있는 카드팩입니다.')}>카드팩 검사</button><span className="save-state" role="status">{saved}</span></div>
 {message&&<p className="notice preserve-lines" role="status">{message}</p>}
 {pending&&<section className="confirm-box"><h2>{pending.name} 열기</h2><p>카드 {pending.cards.length}장 · 그림 {Object.keys(pending.images).length}개. 현재 초안을 이 팩으로 교체합니다. 필요한 작업은 먼저 내보내 주세요.</p>{pending.id==='core'&&<p>기본 팩의 복사본으로 열며 팩 ID는 custom-core로 바꿉니다.</p>}<div className="actions"><button onClick={()=>replace(pending.id==='core'?{...pending,id:'custom-core',name:pending.name+' 복사본'}:pending)}>이 팩 열기</button><button onClick={()=>setPending(null)}>취소</button></div></section>}
 {confirmation&&<section className="confirm-box"><p>{confirmation==='new'?'현재 초안을 새 예시 팩으로 교체할까요?':'선택한 카드와 연결된 사건·스킬을 삭제할까요?'}</p><div className="actions"><button onClick={()=>perform(()=>{if(confirmation==='new')replace(newDraft());else if(card)replace(deleteCard(pack,card.id));})}>확인</button><button onClick={()=>setConfirmation(null)}>취소</button></div></section>}
 {draftBlocked&&<p className="notice warning">초안을 읽지 못해 자동 저장을 멈췄습니다. 기존 원본을 유지합니다. 새 팩을 만들거나 파일을 열면 다시 저장합니다.</p>}
 <fieldset disabled={!ready||draftBlocked} className="editor-root-fields"><details className="panel pack-meta"><summary>팩 정보 · {pack.name} · 개정 {pack.revision}</summary><div className="editor-row"><TextField label="팩 이름" value={pack.name} onChange={name=>update(p=>{p.name=name;})}/><TextField label="팩 ID (영문 소문자·숫자·하이픈)" value={pack.id} onChange={id=>update(p=>{p.id=id;})}/><NumberField label="개정 번호" value={pack.revision} min={1} max={1000000} onChange={revision=>update(p=>{p.revision=revision;})}/><TextField label="제작자" value={pack.author} onChange={author=>update(p=>{p.author=author;})}/></div><TextField label="팩 소개" value={pack.description} multi onChange={description=>update(p=>{p.description=description;})}/><p className="reason">수정판은 같은 팩 ID와 더 높은 개정으로 내보내세요. 카드를 따로 배포하려면 새 팩 ID를 사용하세요.</p></details>
 <div className="editor-layout"><aside className="editor-sidebar"><h2>서포트 {pack.cards.length}장</h2><div className="editor-card-list">{pack.cards.map(c=><button key={c.id} aria-pressed={card?.id===c.id} onClick={()=>setSelected(c.id)}><CardAvatar card={c} content={pack}/><span><strong>{c.name||'이름 없음'}</strong><small>{c.title}</small></span></button>)}</div><div className="actions"><button disabled={pack.cards.length>=100} onClick={()=>perform(()=>{const id=uid();setPack(addTemplate(pack,id));setSelected(id);})}>새 카드 추가</button>{card&&<><button disabled={!!validation||pack.cards.length>=100} onClick={()=>perform(()=>{const id=uid();setPack(duplicateCard(pack,card.id,id));setSelected(id);})}>현재 카드 복제</button><button onClick={()=>setConfirmation('delete')}>현재 카드 삭제</button></>}</div></aside>
 <main className="editor-main">{card?<><div className="editor-card-title"><CardAvatar card={card} content={pack}/><div><h2>{card.name||'새 파트너'}</h2><p>{card.title}</p><small className="reason">카드 ID · {card.id}</small></div></div><nav className="editor-tabs" aria-label="카드 편집 항목">{['인물','훈련','스킬','사건','미리 보기'].map(t=><button aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='인물'&&<section className="panel"><div className="editor-row"><TextField label="인물 이름" value={card.name} onChange={name=>changeCard(c=>{c.name=name;})}/><TextField label="카드 제목" value={card.title} onChange={title=>changeCard(c=>{c.title=title;})}/><label className="editor-field">학년<select value={card.grade} onChange={e=>changeCard(c=>{c.grade=Number(e.target.value) as 1|2|3;})}>{[1,2,3].map(g=><option key={g} value={g}>{g}학년</option>)}</select></label><TextField label="인물 역할" value={card.role} onChange={role=>changeCard(c=>{c.role=role;})}/><label className="editor-field">카드 색<input type="color" value={card.color} onChange={e=>changeCard(c=>{c.color=e.target.value;})}/></label></div><TextField label="인물 소개" value={card.description} multi onChange={description=>changeCard(c=>{c.description=description;})}/><label className="file-button">일러스트 넣기<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('PNG·JPEG·WebP 그림을 2MB 이하로 넣어 주세요.');const data=base64(new Uint8Array(await f.arrayBuffer()));setPack(previous=>setCardImage(previous,card.id,{mime:f.type as CardPack['images'][string]['mime'],data},uid()));setMessage('일러스트를 담았습니다. 파일 내보내기에 함께 포함됩니다.');}catch(error){setMessage(errorText(error));}}}/></label>{card.portrait&&<button onClick={()=>update(p=>{const c=p.cards.find(c=>c.id===card.id)!,old=c.portrait;delete c.portrait;if(old&&!p.cards.some(c=>c.portrait===old))delete p.images[old];})}>일러스트 제거</button>}<p className="reason">세로 그림 권장 · PNG/JPEG/WebP 2MB 이하. 없는 그림은 이름 아이콘으로 표시합니다.</p></section>}
 {tab==='훈련'&&<section className="panel"><label className="editor-field">전문 능력<select value={card.specialty||'recovery'} onChange={e=>changeCard(c=>{c.specialty=e.target.value==='recovery'?null:e.target.value as SupportCard['specialty'];})}>{primaryNames.map(k=><option key={k} value={k}>{primaryLabels[k]}</option>)}<option value="recovery">회복 (전문 능력 없음)</option></select></label><p className="reason">전문 능력에 동행 +5, 훈련 일치 +5, 인연 60부터 +5가 적용됩니다. 능력 보너스는 카드당 최대 +15이며 합동은 체력 효과만 더합니다. 훈련 목록은 제작기 미리보기용이며 실제 배치는 다섯 훈련에 동일하게 배정합니다.</p>{roles.map(role=><fieldset className="check-grid" key={role}><legend>{roleLabel(role)} 선호 훈련 (1~3개)</legend>{activities({role,phase:'weekday'}).map(a=><label key={a.id}><input type="checkbox" checked={card.training[role].some(id=>id===a.id)} onChange={e=>changeCard(c=>{c.training={...c.training,[role]:e.target.checked?[...c.training[role],a.id]:c.training[role].filter(id=>id!==a.id)};})}/>{a.title}</label>)}</fieldset>)}<div className="editor-row">{(['energy','stress','jointEnergy'] as const).map(k=><NumberField key={k} label={{energy:'동행 체력 회복',stress:'동행 스트레스 변화',jointEnergy:'합동 추가 체력'}[k]} value={card.bonus[k]} min={k==='stress'?-4:0} max={k==='stress'?0:6} onChange={value=>changeCard(c=>{c.bonus[k]=value;})}/>)}</div></section>}
 {tab==='스킬'&&<><section className="panel"><h2>역할별 성장 계열</h2><div className="actions">{roles.map(r=><button key={r} onClick={()=>perform(()=>setPack(addSkillPair(pack,card.id,r,uid())))}>{roleLabel(r)}용 새 계열 만들기</button>)}</div><p className="reason">일반 스킬 → 이 카드의 고유 상위 스킬을 연결하세요. 마지막 성장 사건 양쪽 선택지에 상위 개방 보상을 넣습니다.</p>{roles.map(role=><div className="editor-row" key={role}>{(['hints','ultimates'] as const).map(kind=><label className="editor-field" key={kind}>{roleLabel(role)} {kind==='hints'?'일반 조언':'고유 상위'}<select value={card[kind][role]||''} onChange={e=>setPack(setCardSkill(pack,card.id,role,kind,e.target.value||null))}><option value="">없음</option>{pack.skills.filter(k=>(k.role==='both'||k.role===role)&&(kind==='hints'?k.tier==='normal':k.tier==='advanced'&&k.owner===card.id)).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label>)}</div>)}</section>{pack.skills.filter(k=>cardSkills.has(k.id)).map(skill=><SkillEditor key={skill.id} skill={skill} pack={pack} onChange={fn=>update(p=>fn(p.skills.find(k=>k.id===skill.id)!))}/>)}</>}
 {tab==='사건'&&<><p className="notice">고유 사건은 인연과 선행 사건을 충족하면 우선 추첨됩니다. 어느 선택지를 골라도 다음 단계로 이어지도록 설계하세요.</p>{cardEvents.map(e=><EventEditor key={e.id} event={e} card={card} pack={pack} onChange={fn=>update(p=>fn(p.events.find(k=>k.id===e.id)!))} onDelete={()=>update(p=>{p.events=p.events.filter(k=>k.id!==e.id);})}/>)}<button onClick={()=>update(p=>{p.events.push({id:`${card.id}_event_${crypto.randomUUID().slice(0,8)}`,owner:card.id,kind:'daily',bond:0,title:'새로운 만남',text:'훈련을 마치고 파트너와 이야기를 나눴다.',choices:[0,1].map(n=>({label:n?'잠깐 쉬며 이야기한다':'함께 연습을 돌아본다',reply:'다음 연습의 목표를 정했다.',gains:{},energy:0,stress:0,points:0,trust:0,bond:4,hints:[],unlocks:[]})) as unknown as EncounterDefinition['choices']});})}>사건 추가</button></>}
 {tab==='미리 보기'&&<Preview pack={pack} card={card}/>}</>:<section className="panel">카드를 추가하면 편집을 시작할 수 있습니다.</section>}
 {validation&&<details className="validation-errors" open><summary>수정이 필요한 항목 · 내보내기 전 해결해 주세요</summary><pre>{validation}</pre></details>}</main></div></fieldset><footer>마지막 여름 · CARD STUDIO · 카드팩 형식 2 / 규칙 first-year-1</footer></div>;
}

function SkillEditor({skill:k,pack,onChange}:{skill:SkillDefinition;pack:CardPack;onChange:(fn:(s:SkillDefinition)=>void)=>void}){
 return <section className="panel editor-skill"><h3>{k.tier==='advanced'?'상위':'일반'} · {k.name}</h3><p className="reason">{describeSkill(k)}</p><div className="editor-row"><TextField label="스킬 이름" value={k.name} onChange={name=>onChange(s=>{s.name=name;})}/><NumberField label="습득 포인트" value={k.cost} min={6} max={60} onChange={cost=>onChange(s=>{s.cost=cost;})}/><label className="editor-field">사용 역할<select value={k.role} onChange={e=>onChange(s=>{s.role=e.target.value as typeof s.role;for(const key of requirementNames)if(!skillAbilityNames(s.role).includes(key))delete s.requires[key];})}><option value="both">공통</option><option value="batter">타자</option><option value="pitcher">투수</option></select></label></div><TextField label="스킬 소개" value={k.description} onChange={description=>onChange(s=>{s.description=description;})}/>{k.tier==='advanced'&&<label className="editor-field">선행 일반 스킬<select value={k.prerequisite||''} onChange={e=>onChange(s=>{s.prerequisite=e.target.value;s.family=pack.skills.find(k=>k.id===e.target.value)!.family;})}>{pack.skills.filter(s=>s.tier==='normal').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<details><summary>습득에 필요한 1차·종합 능력</summary><div className="editor-row">{requirementNames.filter(stat=>skillAbilityNames(k.role).includes(stat)).map(stat=><NumberField label={stat==='overall'?'종합 능력':primaryLabels[stat]} key={stat} value={k.requires[stat]||0} min={0} max={stat==='overall'?100:1500} onChange={v=>onChange(s=>{if(v)s.requires[stat]=v;else delete s.requires[stat];})}/>)}</div></details><h4>발동 조건 · 모두 충족</h4>{k.conditions.map((c,i)=><div className="editor-rule" key={i}><ConditionFields value={c} onChange={value=>onChange(s=>{s.conditions[i]=value;})}/><button onClick={()=>onChange(s=>{s.conditions.splice(i,1);})}>조건 삭제</button></div>)}<button disabled={k.conditions.length>=5} onClick={()=>onChange(s=>{s.conditions.push({kind:'inning',min:7,max:99});})}>조건 추가</button><h4>발동 효과</h4>{k.effects.map((e,i)=><div className="editor-rule" key={i}><EffectFields value={e} onChange={value=>onChange(s=>{s.effects[i]=value;})}/><button disabled={k.effects.length===1} onClick={()=>onChange(s=>{s.effects.splice(i,1);})}>효과 삭제</button></div>)}<button disabled={k.effects.length>=2} onClick={()=>onChange(s=>{s.effects.push({kind:'probability',from:'out',to:'single',amount:.02});})}>효과 추가</button></section>;
}
function EventEditor({event:e,card,pack,onChange,onDelete}:{event:EncounterDefinition;card:SupportCard;pack:CardPack;onChange:(fn:(event:EncounterDefinition)=>void)=>void;onDelete:()=>void}){
 const skillName=(id:string)=>pack.skills.find(k=>k.id===id)?.name||id;
 return <details className="panel editor-event"><summary>{e.kind==='growth'?'성장':'일상'} · {e.title} · 인연 {e.bond}</summary><p className="reason">사건 ID · {e.id}</p><div className="editor-row"><TextField label="사건 제목" value={e.title} onChange={title=>onChange(e=>{e.title=title;})}/><label className="editor-field">사건 종류<select value={e.kind} onChange={v=>onChange(e=>{e.kind=v.target.value as typeof e.kind;})}><option value="daily">반복 일상</option><option value="growth">한 번의 성장</option></select></label><NumberField label="필요 인연" value={e.bond} min={0} max={100} onChange={bond=>onChange(e=>{e.bond=bond;})}/><label className="editor-field">선행 성장 사건<select value={e.previous||''} onChange={v=>onChange(e=>{if(v.target.value)e.previous=v.target.value;else delete e.previous;})}><option value="">없음</option>{pack.events.filter(x=>x.owner===e.owner&&x.kind==='growth'&&x.id!==e.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div><TextField label="사건 본문" value={e.text} multi onChange={text=>onChange(e=>{e.text=text;})}/>{e.choices.map((c,i)=><fieldset className="editor-choice" key={i}><legend>선택지 {i+1}</legend><TextField label="선택 문구" value={c.label} onChange={label=>onChange(e=>{e.choices[i].label=label;})}/><TextField label="선택 후 대사" value={c.reply} multi onChange={reply=>onChange(e=>{e.choices[i].reply=reply;})}/><div className="editor-row">{primaryNames.map(k=><NumberField key={k} label={primaryLabels[k]} value={c.gains[k]||0} min={-85} max={85} onChange={v=>onChange(e=>{if(v)e.choices[i].gains[k]=v;else delete e.choices[i].gains[k];})}/>)}{(['energy','stress','points','trust','bond'] as const).map(k=><NumberField key={k} label={{energy:'체력',stress:'스트레스',points:'스킬 Pt',trust:'감독 신뢰',bond:'인연'}[k]} value={c[k]} min={{energy:-15,stress:-16,points:0,trust:-3,bond:0}[k]} max={{energy:16,stress:10,points:8,trust:3,bond:8}[k]} onChange={v=>onChange(e=>{e.choices[i][k]=v;})}/>)}</div>{(['hints','unlocks'] as const).map(key=><fieldset className="check-grid" key={key}><legend>{key==='hints'?'일반 스킬 힌트':'상위 스킬 개방'}</legend>{[...new Set(Object.values(key==='hints'?card.hints:card.ultimates).filter((id):id is string=>Boolean(id)))].map(id=><label key={id}><input type="checkbox" checked={c[key].includes(id)} onChange={v=>onChange(e=>{e.choices[i][key]=v.target.checked?[...e.choices[i][key],id]:e.choices[i][key].filter(x=>x!==id);})}/>{skillName(id)}</label>)}</fieldset>)}</fieldset>)}<button onClick={onDelete}>이 사건 삭제</button></details>;
}
