import type {SkillCondition,SkillEffect} from '../cards/schema.ts';
import {tacticIds,outcomeIds} from '../cards/schema.ts';
import {resultLabels} from '../cards/description.ts';
export function TextField({label,value,onChange,multi=false}:{label:string;value:string;onChange:(value:string)=>void;multi?:boolean}){return <label className="editor-field">{label}{multi?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={4}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
export function NumberField({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number;step?:number}){return <label className="editor-field">{label}<input type="number" value={Number.isFinite(value)?value:''} min={min} max={max} step={step} onChange={e=>onChange(e.target.value===''?0:Number(e.target.value))}/></label>;}
export const conditionDefaults:Record<SkillCondition['kind'],SkillCondition>={tactic:{kind:'tactic',values:['contact']},inning:{kind:'inning',min:7,max:99},outs:{kind:'outs',min:2,max:2},energy:{kind:'energy',min:0,max:44},stress:{kind:'stress',min:70,max:100},runners:{kind:'runners',present:true},score:{kind:'score',value:'behind'},opponent:{kind:'opponent',values:['wild']}};
const conditionLabels={tactic:'작전',inning:'이닝',outs:'아웃',energy:'체력',stress:'스트레스',runners:'주자',score:'점수 차',opponent:'상대 유형'};
export function RoleScope({value,onChange}:{value?:'batter'|'pitcher';onChange:(value?:'batter'|'pitcher')=>void}){return <label className="editor-field">적용 역할<select value={value||'both'} onChange={e=>onChange(e.target.value==='both'?undefined:e.target.value as 'batter'|'pitcher')}><option value="both">스킬 공통</option><option value="batter">타자만</option><option value="pitcher">투수만</option></select></label>;}
export function ConditionFields({value:c,onChange}:{value:SkillCondition;onChange:(value:SkillCondition)=>void}){return <div className="editor-row"><label className="editor-field">조건 종류<select value={c.kind} onChange={e=>onChange(structuredClone(conditionDefaults[e.target.value as SkillCondition['kind']]))}>{Object.entries(conditionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><RoleScope value={c.role} onChange={role=>onChange({...c,role})}/>{'min' in c&&<><NumberField label="최소" value={c.min} min={c.kind==='inning'?1:0} max={c.kind==='outs'?2:c.kind==='inning'?99:100} onChange={min=>onChange({...c,min})}/><NumberField label="최대" value={c.max} min={c.kind==='inning'?1:0} max={c.kind==='outs'?2:c.kind==='inning'?99:100} onChange={max=>onChange({...c,max})}/></>}{c.kind==='tactic'&&<fieldset className="check-grid"><legend>허용 작전 (최대 4)</legend>{tacticIds.map(id=><label key={id}><input type="checkbox" checked={c.values.includes(id)} onChange={e=>onChange({...c,values:e.target.checked?[...c.values,id]:c.values.filter(v=>v!==id)})}/>{{contact:'정확하게',power:'장타',patient:'공 고르기',bunt:'번트',fastball:'직구',breaking:'변화구',control:'맞혀 잡기',chase:'유인구'}[id]}</label>)}</fieldset>}{c.kind==='runners'&&<label className="editor-field">주자<select value={c.present?'yes':'no'} onChange={e=>onChange({...c,present:e.target.value==='yes'})}><option value="yes">있을 때</option><option value="no">없을 때</option></select></label>}{c.kind==='score'&&<label className="editor-field">우리 팀 상황<select value={c.value} onChange={e=>onChange({...c,value:e.target.value as typeof c.value})}><option value="behind">지는 중</option><option value="tied">동점</option><option value="ahead">이기는 중</option></select></label>}{c.kind==='opponent'&&<fieldset className="check-grid"><legend>상대 유형</legend>{(['wild','fast','tired','power','patient'] as const).map(id=><label key={id}><input type="checkbox" checked={c.values.includes(id)} onChange={e=>onChange({...c,values:e.target.checked?[...c.values,id]:c.values.filter(v=>v!==id)})}/>{{wild:'제구 불안',fast:'직구',tired:'피로',power:'장타',patient:'선구안'}[id]}</label>)}</fieldset>}</div>;}
export function EffectFields({value:e,onChange}:{value:SkillEffect;onChange:(value:SkillEffect)=>void}){return <div className="editor-row"><label className="editor-field">효과 종류<select value={e.kind} onChange={v=>onChange(v.target.value==='probability'?{kind:'probability',from:'out',to:'single',amount:.02}:v.target.value==='burden'?{kind:'burden',amount:1}:{kind:'fatigue',amount:.5})}><option value="probability">결과 확률 이동</option><option value="burden">투구 부담 감소</option><option value="fatigue">체력 불이익 완화</option></select></label><RoleScope value={e.role} onChange={role=>onChange({...e,role})}/>{e.kind==='probability'?<>{(['from','to'] as const).map(key=><label className="editor-field" key={key}>{key==='from'?'줄일 결과':'늘릴 결과'}<select value={e[key]} onChange={v=>onChange({...e,[key]:v.target.value})}>{outcomeIds.map(id=><option value={id} key={id}>{resultLabels[id]}</option>)}</select></label>)}<NumberField label="이동량 (%p)" value={+(e.amount*100).toFixed(3)} min={.1} max={8} step={.1} onChange={amount=>onChange({...e,amount:amount/100})}/></>:<NumberField label={e.kind==='burden'?'부담 감소량':'완화율 (0.1~1)'} value={e.amount} min={e.kind==='burden'?1:.1} max={e.kind==='burden'?3:1} step={e.kind==='burden'?1:.05} onChange={amount=>onChange({...e,amount})}/>}</div>;}
